server:
  port: 8084
  
  
spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/hotelservice
      username: postgres
      password: root
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: HOTEL-SERVICE

  config:
    import: configserver:http://localhost:8087

  graphql:
    path: /g
springdoc:
  api-docs:
    path: /hotel-docs